package com.appsquadz.mvvmwithretrofit.model

data class MenuTypeList(
    var id: String,
    var name:String,
    var description:String,
    var channel_url:String,
    var creation_time:String,
    var image:String,
    var is_app:String,
    var is_caching:String,
    var is_likes:String,
    var is_tv:String,
    var is_web:String,
    var likes:String,
    var position:String,
    var status:String,
    var season_id:String,
    var category_id:String,
    var custom_promo_video:String,
    var season_thumbnail:String,
    var season_title:String,
    var short_desc:String,
    var short_video:String,
    var yt_promo_video:String,
    var thumbnail_url:String,
    var thumbnail_url1:String,
    var video_desc:String,
    var video_title:String,
    var youtube_likes:String,
    var youtube_url:String,
    var youtube_views:String,
    var author_name:String,
    var episode_id:String,
    var episode_title:String,
    var token:String,
    var yt_episode_url:String,
    var episode_description:String,
    var custom_episode_url:String,
    var profile_image:String,
    var thumbnail1:String
)
